[inet_http_server]
nodename = node-2
port = 127.0.0.1:9001
;remote_1_node = node-1
remote_1_port = 127.0.0.1:9002
remote_1_user = test
remote_1_password = test

[program:test-1]
#directory = /c/Users/stou/supervisord/src/github.com
command = python hello.py --port 5000
stdout_logfile = test-1-stdout.log
stderr_logfile = test-1-stderr.log
stdout_logfile_maxbytes = 1MB
stderr_logfile_maxbytes = 1MB
stdout_logfile_backups = 0
stderr_logfile_backups = 0

[program:test-2]
#directory = /c/Users/stou/supervisord/src/gitgub.com
command = python hello.py --port 5001

[program:test-3]
command = ./env-test.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:echo]
command = python echo.py

[group:test-group]
programs = test-1,test-2,test-3
